baseURL = "https://hikingc.github.io"
locale = "en-us"
relativeURLs = true
title = "Nice Polar Blog"
theme = "SimpleTheme"

[build]
writeStats = true

[menu]

[[menu.main]]
homepage = "Posts"
name = "Posts"
url = "/posts/"
weight = 10

[params]
dateFormat = "02 of January of 2006"
copyright = "hikingc" # Will be displayed on Footer
creationYearCopyright = "2021" # Put the year you started on here
logo = "/img/PolarBear.svg" # Supports SVG.
logoalt = "A white polar bear" # alt description of the logo.
  [params.author]
    name = "hikingc"
    github = "hikingc" # https://github.com/XXXX


[permalinks]
posts = ':section/:year/:month/:title/'

[markup.goldmark.parser.attribute]
block = true
[markup]
  [markup.highlight]
    style = 'nord'
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
